### ISSUE TITLE
Shebang incompatible with OSX using NVM

### ISSUE THREAD

**Issue by insanity54** [educastellano/jsonlint-tree#3]
The first line of this utility is `#!/usr/local/bin/node`, a path which is empty on OSX when using [Node Version Manager](https://github.com/creationix/nvm). 

Thus, this utility when run on OSX with Node installed via NVM produces--

```
-bash: /Users/chris/.nvm/versions/node/v4.5.0/bin/jsonlint-tree: /usr/local/bin/node: bad interpreter: No such file or directory
```

A solution which would help this utility run on the most platforms would be to use this shebang instead--

```
#!/usr/bin/env node
```

**Comment by educastellano** [comment]
fixed and published in jsonlint-tree@1.0.1 🎉
